language: android
jdk: oraclejdk7

env:
  matrix:
    - ANDROID_TARGET=android-23  ANDROID_ABI=armeabi-v7a

android:
  components:
    - tools
    - android-23
    - build-tools-23.0.2
    - extra-android-m2repository
    - extra-google-m2repository

script: ./gradlew clean build -PtravisBuild -i

after_failure: "cat /home/travis/build/Zlate87/sample-transport-app/app/build/outputs/lint-results.xml"