language: android
jdk: oraclejdk7

env:
  matrix:
    - ANDROID_TARGET=android-23  ANDROID_ABI=armeabi-v7a

android:
  components:
    - android-23
    - build-tools-23.0.2

script: ./gradlew clean build